---
- hosts: all

  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

  roles:
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint
      become: yes
      when: (docker_enabled | default(False))

  tasks:
  - import_tasks: tasks/core.yml
    tags: core

  - import_tasks: tasks/secret.yml
    when: (secret_enabled | default(False))
    tags: secret

  - import_tasks: tasks/docker.yml
    when: (docker_enabled | default(False))
    tags: docker

  - import_tasks: tasks/emacs.yml
    when: (emacs_enabled | default(False))
    tags: emacs

  - import_tasks: tasks/mail.yml
    when: (mail_enabled | default(False))
    tags: mail



  - import_tasks: tasks/emacs_stable.yml
    when: (stable_enabled | default(False))
    tags: emacsstable

  - import_tasks: tasks/web.yml
    tags: web

  - import_tasks: tasks/org.yml
    when: (org_enabled | default(False))
    tags: org

  - import_tasks: tasks/r.yml
    when: (r_enabled | default(False))
    tags: r

  - import_tasks: tasks/python.yml
    when: (python_enabled | default(False))
    tags: python

  - import_tasks: tasks/bib.yml
    when: (bib_enabled | default(False))
    tags: bib


  - import_tasks: tasks/zsh.yml
    when: (zsh_enabled | default(False))
    tags: zsh

  - import_tasks: tasks/tmux.yml
    when: (tmux_enabled | default(False))
    tags: tmux

  - import_tasks: tasks/write.yml
    when: (write_enabled | default(False))
    tags: write

  - import_tasks: tasks/inspiration.yml
    when: (inspiration_enabled | default(False))
    tags: inspiration

  - import_tasks: tasks/remote.yml
    when: (remote_enabled | default(False))
    tags: remote
