---
- name: install core packages
  apt:
    name: ['zsh', 'ispell', 'aspell-fr', 'pass', 'vim', 'git', 'make', 'msmtp', 'isync', 'htop', 'curl', 
    'tmux', 'silversearcher-ag', 'ctags', 'unison', 'virtualenv', "python3-notmuch"]
    state: latest
    install_recommends: yes
    update_cache: yes
  become: yes

- name: install python core packages
  apt:
    name: ['python3', 'python3-pip', 'python3-virtualenv', 'python-pip']
    state: latest
    install_recommends: yes
    update_cache: yes
  become: yes

- name: Install python tools in .pyvenv 
  pip: 
    virtualenv_python: python3.6
    virtualenv: "{{pyvenv_path}}"
    virtualenv_site_packages: yes
    name: ['cookiecutter', 'mkdocs', 'dvc[all]', 'academic', 'doit', 'afew']
    state: latest

- name: Create symlink for python tools
  file: 
    src: '{{pyvenv_path}}/bin/{{ item }}'
    dest: '{{extra_bin_path}}/{{ item }}'
    state: link
  with_items:
    - cookiecutter
    - mkdocs
    - dvc
    - academic
    - doit
    - afew
