---
- name: install python3-pip
  apt:
    name: python3-pip
    state: present
  register: result
  until: result is succeeded
  become: yes

- name: 'Install docker-py'
  pip:
    name: docker-py
    state: present
  register: result
  until: result is succeeded

- name: create docker home
  file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory
  become: yes

- name: add user account to docker group
  user:
    name: "{{ username }}"
    group: docker
    append: yes
  become: yes

- name: update docker home from install default
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config
  become: yes

- name: restart docker
  service:
     name: docker
     state: restarted
  when: docker_config.changed
  become: yes
  tags:
    - skip_ansible_lint
