- name: Create src dir
  file:
    path: '/home/{{username}}/.src/'
    state: directory
  become_user: "{{username}}"

- name: Clone afew
  git: repo=https://github.com/afewmail/afew.git
       dest=~/.src/afew
       accept_hostkey=yes
  become_user: "{{username}}"

- name: Clone org-html-themes
  git: repo=https://github.com/fniessen/org-html-themes.git
       dest=~/.src/org-html-themes
       accept_hostkey=yes
  become_user: "{{username}}"

- name: Clone worgle
  git: repo=https://github.com/OrgTangle/Worgle.git
       dest=~/.src/Worgle
       accept_hostkey=yes
  become_user: "{{username}}"

## install tomb: https://www.dyne.org/software/tomb/
- name: Clone tomb
  git: repo=https://github.com/dyne/Tomb.git
       dest=~/.src/Tomb
       accept_hostkey=yes
  become_user: "{{username}}"

- name: install packages dependencies for tomb
  action: apt pkg={{ item }} state=present install_recommends=yes
  become: yes
  with_items:
    - gnupg
    - cryptsetup
    - pinentry-curses
    - steghide

# - name: install tomb
#   become: yes
#   make:
#     chdir: /home/{{local_username}}/.src/Tomb
#     target: install
 
- name: Fetch ansible nas
  git:
    repo: https://github.com/davestephens/ansible-nas.git
    dest: /home/{{username}}/.src/ansible-nas
  become_user: "{{username}}"

- name: Fetch ansible reveal.js
  git:
    repo: https://github.com/hakimel/reveal.js.git
    dest: /home/{{username}}/.src/reveal.js
  become_user: "{{username}}"

- name: Clone grasp
  git:
    repo: https://github.com/karlicoss/grasp.git
    dest: /home/{{username}}/.src/grasp
  become_user: "{{username}}"

- name: Clone doit
  git:
    repo: https://github.com/pydoit/doit.git
    dest: /home/{{username}}/.src/doit
  become_user: "{{username}}"

- name: doit zsh tab completion
  copy:
    src: /home/{{username}}/.src/doit/zsh_completion_doit
    dest: "{{extra_zshcompletion_path}}/_doit"
    mode: '0644'
  become_user: "{{username}}"
  when: (zsh_enabled | default(False))

- name: Clone fastai
  git:
    repo: https://github.com/fastai/fastai.git
    dest: /home/{{username}}/.src/fastai
  become_user: "{{username}}"

- name: Clone seaborn
  git:
    repo: https://github.com/mwaskom/seaborn.git
    dest: /home/{{username}}/.src/seaborn
  become_user: "{{username}}"

- name: Clone xgboost
  git:
    repo: https://github.com/dmlc/xgboost.git
    dest: /home/{{username}}/.src/xgboost
  become_user: "{{username}}"
