- name: install python core packages
  apt:
    name: [python, python-virtualenv, python-dev, python-setuptools, python-pip, python3, python3-setuptools, python3-dev, python3-pip]
    state: present
    install_recommends: yes
    update_cache: yes
  become: yes
