## install tomb: https://www.dyne.org/software/tomb/
- name: Clone tomb
  git:
    repo: https://github.com/dyne/Tomb.git
    dest: ~/.src/Tomb
  become_user: "{{username}}"

- name: install packages dependencies for tomb
  apt:
    name: [gnupg, cryptsetup, pinentry-curses, steghide]
    state: present
    install_recommends: yes
    update_cache: yes
  become: yes

- name: Check if tomb is installed
  stat:
    path: /usr/local/bin/tomb
  register: tomb_path

- name: install tomb
  make:
    chdir: /home/{{username}}/.src/Tomb
    target: install
  become: yes
  when: tomb_path.stat.exists == false

- name: configure ssh
  blockinfile: 
    dest: "/home/{{username}}/.ssh/config"
    create: yes
    insertbefore: BOF
    block: |
      Host home
          HostName {{home_hostname}}
          IdentityFile ~/.ssh/id_rsa
          User {{home_username}}
          ForwardX11 no

      Host box
          HostName box.caye.fr
          IdentityFile ~/.ssh/id_rsa
          User {{box_username}}
          ForwardX11 no

      Host git
          HostName {{git_hostname}}
          IdentityFile ~/.ssh/id_rsa
          User {{git_username}}
          ForwardX11 no

- name: retrieve secret tomb
  get_url:
    url: "{{secret_url}}"
    dest: "/home/{{username}}/"

- name: clone password store
  git:
    repo: "{{pass_repo}}"
    dest: "/home/{{username}}/.password-store"
