- name: install tmux
  apt:
    name: ['tmux']
    state: latest
    install_recommends: yes
    update_cache: yes
  become: yes

- name: Clone oh my tmux
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: "/home/{{username}}/.tmux/"

- name: link oh my tmux
  file:
    src: "/home/{{username}}/.tmux/.tmux.conf"
    dest: "/home/{{username}}/.tmux.conf"
    state: link

- name: add zsh tmux plugin
  lineinfile: 
    dest: "/home/{{username}}/.zshrc"
    state: present
    regexp: 'plugins=\(((?!.*?(tmux)).*)\)$'
    line: plugins=(\1 tmux)
    backrefs: yes
  when: (zsh_enabled | default(False))

- name: tmux force auto start with zsh
  lineinfile: 
    dest: "/home/{{username}}/.zshrc"
    insertbefore: BOF
    line: ZSH_TMUX_AUTOSTART=true
  when: (tmux_autostart | default(False))

- name: tmux avoid autoquit
  lineinfile: 
    dest: "/home/{{username}}/.zshrc"
    insertbefore: BOF
    line: ZSH_TMUX_AUTOQUIT=false
  when: (tmux_autostart | default(False))
