---
- name: Create user group
  group:
    name: "{{ username }}"
    state: present
  become: yes

- name: Create user
  user:
    name: "{{ username }}"
    state: present
    group: "{{ username }}"
  become: yes

- name: Create extra bin path
  file:
    path: '{{extra_bin_path}}'
    group: "{{username}}"
    owner: "{{username}}"
    state: directory
  become: yes

- name: add {{extra_bin_path}} to path
  lineinfile: 
    dest: "/home/{{username}}/.zshenv"
    state: present
    regexp: 'export PATH=(["]*)((?!.*?{{extra_bin_path}}).*?):\$PATH(["]*)$'
    line: export PATH=\1\2:{{extra_bin_path}}:$PATH\3
    backrefs: yes
    create: yes
    firstmatch: yes
  when: (zsh_enabled | default(False))

- name: create projects folder
  file:
    path: "/home/{{username}}/projects/opensource/"
    state: directory
    recurse: yes
