- name: install graphic packages
  apt:
    name: ['okular', 'eog', 'unison-gtk']
    state: latest
    install_recommends: yes
    update_cache: yes
  become: yes

- name: install web browser chromium
  apt:
    name: ['chromium-browser']
    state: latest
    install_recommends: yes
    update_cache: yes
  become: yes
